CREATE DATABASE coletivoCatuca;

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT,
	users VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,

	PRIMARY KEY (id)
);

CREATE TABLE public(
	id_public INT AUTO_INCREMENT NOT NULL,
	pub VARCHAR(500) NOT NULL,
	img VARCHAR(100) NOT NULL,
	user_id INT NOT NULL,


	PRIMARY KEY (id_public),
	CONSTRAINT FOREIGN KEY (user_id) REFERENCES users (id)
);

